In [3]:
import numpy as np

coords = np.array([[-1, -1], [1, -1], [1, 1], [-1, 1]])

center = np.mean(coords, axis=0)

distances = np.linalg.norm(coords - center, axis=1)

normalizedCoords = coords / distances[:, np.newaxis]

print(normalizedCoords)


[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [4]:
def badradius(x):
    return x+(x/abs(x) - 1)*(1 + x)

print(badradius(np.array([-2, -1, 1, 2])))

foo = np.array([[10, 1], [11, 2], [12, 3]])
print(foo[:, 1])

[ 0. -1.  1.  2.]
[1 2 3]


In [16]:
def vecLen(vec):
    return np.sqrt(vec[0]*vec[0] + vec[1]*vec[1])

data = np.array([[0,1], [1, 1]])

print(np.apply_along_axis(vecLen, 0, data))


[1.         1.41421356]
