# Shortest path

basic idea: circulate all locations

## how

* find center of all locations
* connect locations in order of angle around center

## unusual

* center is outside of tour: use clustering algorithm to partition problem

In [5]:
import numpy as np
import pandas as pd

cities = pd.read_csv('german-cities.csv')
locations = cities[['lat', 'lng']].to_numpy()
print(locations)

[[52.52   13.405 ]
 [48.7775  9.18  ]
 [48.1375 11.575 ]
 [53.55   10.    ]
 [50.9364  6.9528]
 [50.1106  8.6822]
 [51.2333  6.7833]
 [51.34   12.375 ]
 [51.5167  7.4667]
 [51.4508  7.0131]
 [53.0833  8.8   ]
 [51.05   13.74  ]
 [52.3667  9.7167]
 [49.4539 11.0775]
 [51.4347  6.7625]
 [51.4819  7.2158]
 [51.2667  7.1833]
 [52.0211  8.5347]
 [50.7333  7.1   ]
 [51.9625  7.6256]
 [49.4878  8.4661]
 [49.0092  8.404 ]
 [48.3689 10.8978]
 [50.0825  8.24  ]
 [51.2     6.4333]
 [51.5167  7.1   ]
 [50.7756  6.0836]
 [52.2667 10.5167]
 [50.8333 12.9167]
 [54.3233 10.1394]
 [51.4828 11.9697]
 [52.1317 11.6392]
 [47.995   7.85  ]
 [51.3333  6.5667]
 [49.9833  8.2667]
 [53.8697 10.6864]
 [50.9833 11.0333]
 [51.4967  6.8706]
 [54.0833 12.1333]
 [51.3158  9.4979]
 [51.3667  7.4833]
 [52.4    13.0667]
 [49.2333  7.    ]
 [51.6833  7.8167]
 [49.4811  8.4353]
 [51.4275  6.8825]
 [53.1439  8.2139]
 [52.2833  8.05  ]
 [51.0333  6.9833]
 [49.8722  8.6528]
 [51.1667  7.0833]
 [49.4167  8.7167]
 [51.55    7

In [3]:
import numpy as np

coords = np.array([[-1, -1], [1, -1], [1, 1], [-1, 1]])

center = np.mean(coords, axis=0)

distances = np.linalg.norm(coords - center, axis=1)

normalizedCoords = coords / distances[:, np.newaxis]

print(normalizedCoords)


[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]



basic idea: circulate all locations

how:

* find center of all locations
* connect locations in order of angle around center



In [4]:
def badradius(x):
    return x+(x/abs(x) - 1)*(1 + x)

print(badradius(np.array([-2, -1, 1, 2])))

foo = np.array([[10, 1], [11, 2], [12, 3]])
print(foo[:, 1])

[ 0. -1.  1.  2.]
[1 2 3]


In [16]:
def vecLen(vec):
    return np.sqrt(vec[0]*vec[0] + vec[1]*vec[1])

data = np.array([[0,1], [1, 1]])

print(np.apply_along_axis(vecLen, 0, data))


[1.         1.41421356]
